### ISSUE TITLE
Puppeteer defaults to headless unless explicitly disabled

### ISSUE THREAD

**Issue by cybairfly** [apify/browser-pool#25]
Puppeteer defaults to headless unless explicitly disabled which is the opposite to the Playwright default and how it should behave when run locally. Explicitly passing `headless: false` in launch options fixes it

**Comment by szmarczak** [comment]
@mnmkng Should we fix this now? The change would be breaking.

**Comment by mnmkng** [comment]
I think we can keep the library specific defaults. We do not change any other defaults AFAIK.
