### ISSUE TITLE
Generated `userDataDir` are not removed from the disk

### ISSUE THREAD

**Issue by MSIH** [apify/browser-pool#32]
My /tmp folder is filling up with 1000s of chrome browser session data like cookies and local storage.

```
drwxrwxr-x   3 msihadmin msihadmin    4096 May  3 07:40 z1EvRqWIbNseXvZo2saou
drwxrwxr-x   3 msihadmin msihadmin    4096 May  3 07:38 ZboBqMZWbLjneQ8qXc6l_
drwxrwxr-x   3 msihadmin msihadmin    4096 May  3 07:39 Zg56KutgK36lXDf0Wl1zm
drwxrwxr-x   3 msihadmin msihadmin    4096 May  3 07:36 zJWoqBFejkCaAjxl0SGq_
drwxrwxr-x   3 msihadmin msihadmin    4096 May  3 07:48 ZN1ajYldDtyuiFU1xUbp7
drwxrwxr-x   3 msihadmin msihadmin    4096 May  3 07:36 zqHD899Hx7amfawm5BDRT
drwxrwxr-x   3 msihadmin msihadmin    4096 May  3 07:44 ZtXhTSjYuv_MCKVkrUGRl
drwxrwxr-x   3 msihadmin msihadmin    4096 May  3 07:38 zw13NsDoBSZPxRFCvCtfg
drwxrwxr-x   3 msihadmin msihadmin    4096 May  3 07:51 ZZ66wFo-KSHke6jfozQ7Y
msihadmin@msih004:/tmp$ cd zw13NsDoBSZPxRFCvCtfg/
msihadmin@msih004:/tmp/zw13NsDoBSZPxRFCvCtfg$ cd Default/
msihadmin@msih004:/tmp/zw13NsDoBSZPxRFCvCtfg/Default$ ls
 blob_storage  'Code Cache'   Cookies-journal  'Local Storage'
 Cache          Cookies       GPUCache         'Session Storage'
msihadmin@msih004:/tmp/zw13NsDoBSZPxRFCvCtfg/Default$ 
```

**Comment by szmarczak** [comment]
This works as expected. `userDataDir` is meant to reuse an existing profile and will create a new one if it does not exist.

**Comment by szmarczak** [comment]
Ah, the issue is that it doesn't remove the directories. Reproducible by running the example from readme.

**Comment by szmarczak** [comment]
This happens on both playwright and puppeteer

**Comment by szmarczak** [comment]
It's generated here: https://github.com/apify/browser-pool/blob/2f89cb5273f9b8cfd04c25458bc435bbbc7fa67d/src/launch-context.ts#L80 but it doesn't exist so chrome creates it but doesn't clean it up since it was explicitly provided.

**Comment by szmarczak** [comment]
https://github.com/microsoft/playwright/blob/c4eb2d4b1e17a0de1cea7220be45545c7c524614/src/server/browserType.ts#L146-L149 we don't have to provide userDataDir

**Comment by szmarczak** [comment]
The bug is since https://github.com/apify/browser-pool/commit/f971af904944e4f202f12ee504801e0d1082f3b2

**Comment by szmarczak** [comment]
https://github.com/microsoft/playwright/pull/9069

**Comment by corford** [comment]
I'm hitting what I think is a related issue with `browser-pool` where Firefox refuses to launch if `userDataDir` is not provided or if a path is provided that doesn't exist. Firefox error is: "Your Firefox profile cannot be loaded. It may be missing or inaccessible".

If I pre-create an empty dir (e.g. `/tmp/whatever`) and pass this to `browser-pool` as the `userDataDir`, Firefox loads fine and performs the crawl.
