### ISSUE TITLE
How to use multiple fingerprints with sessions and without proxies?

### ISSUE THREAD

**Issue by A-Posthuman** [apify/browser-pool#67]
Hi, in my particular use case I don't need to use proxies, but I do use multiple sessions via the sessionpool options, and I would like to know how I can have each session (all as part of the same crawler/browserpool and all on same IP address of my server) use its own fingerprint?

Currently when I enable useFingerprints true, I only seem to end up with 1 fingerprint generated each time I start up my crawler and the fingerprint stays the same during all the run's requests and on all the sessions, even when using incognito.

I would like more "variety" in my requests so that not every request from my server's IP looks like the identical fingerprint. Can this be accomplished? Thanks

**Comment by B4nan** [comment]
Should be resolved via #77
